name: docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.9]
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: eep
        channels: nodefaults,conda-forge
        environment-file: conda/dev.yaml

    - name: Build the book
      run: make docs

    - name: GitHub Pages action
      if: ${{ github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
